
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: stud_user
      POSTGRES_PASSWORD: student
      POSTGRES_DB: stud_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    container_name: fastapi-backend
    ports:
      - "7000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      LANGSMITH_API_KEY: "${LANGSMITH_API_KEY}"
      LANGSMITH_TRACING: "false"
      LANGSMITH_ENDPOINT: "https://eu.api.smith.langchain.com"
      LANGSMITH_PROJECT: "stud_assistant"
    volumes:
      - ./backend:/backend
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vue-frontend
    ports:
      - "7070:5173"
      - "5173:5173"
    volumes:
      - ./frontend/stud_assistant:/app
      - /app/node_modules
    restart: always
volumes:
  postgres_data:
